name: 'Install tooling'
runs:
  using: "composite"
  steps:
    - name: 'Check out xbstrap'
      uses: actions/checkout@v6
      with:
        path: 'xbstrap'
        repository: 'popcorn-2/xbstrap'
    - name: Cache tooling
      id: cache-tooling
      uses: actions/cache@v5
      with:
        path: sysroot/tools
        key: ${{ runner.os }}-tools-${{ hashFiles('xbstrap/packages.yml', 'xbstrap/packages/**.yml') }}
    - name: 'Install tools'
      if: steps.cache-tooling.outputs.cache-hit != 'true'
      run: ./xbstrap/pop --sysroot=sysroot --target x86_64-unknown-popcorn --as-build-dep install @dev/llvm:clang,lld @dev/rustc:cargo,rustdoc,clippy,src,rustfmt
