[workspace]
members = [
	"kernel",
	"utils",
	"targa",
	"paging-macros",
	"kernel_exports",
	"kernel_module_macros",
]

[profile.release-with-debug]
inherits = "release"
debug = true

[profile.release-small]
inherits = "release"
opt-level = "z"
