[package]
name = "popcorn2"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]
members = [
	"builder",
	"kernel",
	"bootloader",
	"utils",
	"targa",
	"ranged_btree",
	"kernel_module_macros",
	"elf",
	"macros",
	"kernel_api",
	"kernel_default_heap",
	"bitmap_allocator",
	"test_harness",
    "linked_list_allocator",
	"arena_heap",
]

[profile.release]
lto = "thin"
debug = "full"

[profile.dev.package.kernel_api]
opt-level = 2

[profile.dev.package.unwinding]
opt-level = 2

[workspace.lints.rust]
ambiguous_negative_literals = "warn"
closure_returning_async_block = "warn"
deref_into_dyn_supertrait = "deny"
elided_lifetimes_in_paths = "warn"
fuzzy_provenance_casts = "deny"
impl_trait_overcaptures = "warn"
impl_trait_redundant_captures = "warn"
keyword_idents_2024 = "forbid"
let_underscore_drop = "warn"
lossy_provenance_casts = "deny"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
missing_unsafe_on_extern = "forbid"
#multiple_supertrait_upcastable = "warn"
#must_not_suspend = "warn"
non_ascii_idents = "forbid"
redundant_imports = "warn"
redundant_lifetimes = "warn"
#resolving_to_items_shadowing_supertrait_items = "warn"
rust_2024_incompatible_pat = "deny"
rust_2024_prelude_collisions = "deny"
#shadowing_supertrait_items = "warn"
single_use_lifetimes = "warn"
trivial_numeric_casts = "warn"
unit_bindings = "warn"
unsafe_attr_outside_unsafe = "forbid"
unsafe_op_in_unsafe_fn = "forbid"
unused_crate_dependencies = "warn"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"
# unused_qualifications = "warn" # seems to cause ICE?
variant_size_differences = "warn"

ellipsis_inclusive_range_patterns = "forbid"
function_casts_as_integer = "deny"
improper_ctypes = "deny"
improper_ctypes_definitions = "deny"
inline_no_sanitize = "deny"
integer_to_ptr_transmutes = "forbid"
internal_eq_trait_method_impls = "forbid"
internal_features = "deny"
invalid_doc_attributes = "forbid"
invalid_value = "forbid"
missing_abi = "deny"
no_mangle_generic_items = "forbid"
ptr_to_integer_transmute_in_consts = "forbid"
static_mut_refs = "forbid"
uncommon_codepoints = "forbid"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kernel_version, values("0.1.0"))', 'cfg(kasan, values(none()))'] }
unfulfilled_lint_expectations = "deny"
unnecessary_transmutes = "deny"
unpredictable_function_pointer_comparisons = "forbid"
unsupported_calling_conventions = "forbid"

[workspace.lints.clippy]
question_mark = "allow" # `let Some(...) = ... else { return None; };` is clearer to spot
significant_drop_tightening = "allow" # too many false positives
needless_continue = "allow" # cleaner to have match with break/continue blocks than just empty block

disallowed_types = "deny"

nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }

alloc_instead_of_core = "warn"
allow_attributes = "warn"
allow_attributes_without_reason = "warn"
clone_on_ref_ptr = "warn"
decimal_literal_representation = "warn"
default_union_representation = "warn"
doc_include_without_cfg = "warn"
doc_paragraphs_missing_punctuation = "warn"
empty_drop = "warn"
empty_enum_variants_with_brackets = "warn"
# expect_used = "warn"
field_scoped_visibility_modifiers = "warn"
float_arithmetic = "warn"
float_cmp_const = "warn"
get_unwrap = "warn"
# indexing_slicing = "warn"
infinite_loop = "warn"
inline_asm_x86_att_syntax = "warn"
map_with_unused_argument_over_ranges = "warn"
min_ident_chars = "warn"
missing_assert_message = "warn"
mixed_read_write_in_expression = "warn"
module_name_repetitions = "warn"
multiple_inherent_impl = "warn"
mutex_atomic = "warn"
mutex_integer = "warn"
negative_feature_names = "warn"
non_zero_suggestions = "warn"
# panic = "warn"
partial_pub_fields = "warn"
pub_without_shorthand = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
redundant_type_annotations = "warn"
renamed_function_params = "warn"
same_name_method = "warn"
self_named_module_files = "warn"
semicolon_outside_block = "warn"
separated_literal_suffix = "warn"
shadow_unrelated = "warn"
string_add = "warn"
string_lit_chars_any = "warn"
suspicious_xor_used_as_pow = "warn"
tests_outside_test_module = "warn"
todo = "warn"
try_err = "warn"
undocumented_unsafe_blocks = "warn"
unnecessary_safety_comment = "warn"
unnecessary_safety_doc = "warn"
unnecessary_self_imports = "warn"
unneeded_field_pattern = "warn"
unused_result_ok = "warn"
# unused_trait_names = "warn"
# unwrap_used = "warn"
wildcard_dependencies = "warn"

[workspace.lints.rustdoc]
missing_crate_level_docs = "warn"
missing_doc_code_examples = "warn"
invalid_codeblock_attributes = "deny"
invalid_html_tags = "deny"
invalid_rust_codeblocks = "deny"
