[package]
name = "popcorn2"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]
members = [
	"builder",
	"kernel",
	"bootloader",
	"utils",
	"psf",
	"targa",
	"ranged_btree",
	"kernel_module_macros",
	"elf",
	"macros",
	"popfs",
	"kernel_api",
	"kernel_default_heap",
	"bitmap_allocator",
	"test_harness",
	"ranged_btree_allocator",
	"arena_heap",
]

[profile.release]
lto = "off"
debug = "full"

[profile.dev.package.kernel_api]
opt-level = 2

[profile.dev.package.unwinding]
opt-level = 2
