disallowed-macros = [
	{ path = "kernel_api::dbg", reason = "The dbg! macro is intended as a debugging tool. It should not be present in released software or committed to a version control system." }
]
allow-expect-in-tests = true
allowed-idents-below-min-chars = ["..", "r", "g", "b", "a"]
