[package]
name = "kernel_default_heap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kernel_api = { version = "0.1.0", path = "../kernel_api" }
log = "0.4.20"
