[package]
name = "kernel_api"
version = "1.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-queue = { version = "0.3.12", default-features = false, features = ["alloc"] }
futures = { version = "0.3.31", default-features = false }
lock_api = "0.4.11"
log = "0.4.20"
parking_lot = { version = "0.12.1", optional = true, features = ["deadlock_detection"] }
libc = { version = "0.2.176", optional = true }
hashbrown = { version = "0.14.5" }

[features]
use_std = ["parking_lot", "hashbrown/ahash", "libc"]
full = []
default = ["full"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kernel_version, values("0.1.0"))', 'cfg(kasan, values(none()))'] }
