use alloc::sync::{Arc, Weak};
use core::mem;
use core::num::NonZeroU16;
use log::{debug, warn};
use crate::prelude::percpu_v2;
use super::{current_thread, scheduler, ThreadId, yield_now, scheduler::Scheduler, ThreadState, PointerState};

/// Park the current thread until it is woken up
///
/// This will park the thread until a [`WakeTrigger`] for this park event wakes the thread.
/// The kernel guarantees that this function will not return unless either there is an error
/// when parking the thread, or the thread is woken.
///
/// [`WakeTrigger`]s are generated by `park()`, and added to wakers with [`Waker::add_wake_trigger()`].
/// A [`WakeTrigger`] will only wake a thread if it was generated for the current park event. This means
/// that a [`WakeTrigger`] will only wake a thread once, even if [`wake()`](WakeTrigger::wake) is
/// repeatedly called.
///
/// # Errors
///
/// # Examples
///
/// ```no_run
/// use kernel::threading::park;
/// use core::time::Duration;
///
/// static TIMER: TimerWaker = /* ... */;
///
/// // This call will return after one second
/// park(&[&TIMER.waker_for(Duration::from_secs(1)]).expect("failed to park thread");
///
/// // This call will never return, even if the timer interrupt goes off again, unless
/// // there was an error in `park`
/// park(&[]).expect("failed to park thread");
/// unreachable!();
///
/// # Atomicity
///
/// The entirety of a call to `park()` executes atomically - if the thread is woken by a valid [`WakeTrigger`]
/// before `park()` has finished executing, it will act like [`yield_now()`], and a thread will never get stuck
/// waiting for an event that has already occurred.
///
/// This means the following code is guaranteed to always make progress:
/// ```rust
/// # use kernel::non_zero;
/// use kernel::threading::{park, WakeReason, Waker, WakeTrigger};
/// 
/// struct ImmediateWaker;
/// 
/// impl Waker for ImmediateWaker {
///     fn add_wake_trigger(&self, wake_trigger: WakeTrigger) {
///         wake_trigger.wake(WakeReason::Custom(non_zero!(1)));
///     }
/// }
///
/// park(&[&ImmediateWaker]).expect("failed to park thread");
/// ```
pub fn park(wakers: &[&dyn Waker]) -> Result<WakeReason, ParkError> {
	let id = current_thread();
	debug!("Parking thread {:?}", id.unwrap());
	let weak_ptr = {
		let mut guard = percpu_v2!(current_thread).write();
		let thread = guard.as_mut().expect("Cannot park when not running a thread").tcb_mut();
		let park_state = Arc::new(ParkGaurd { thread_id: *thread.thread_id });
		let weak_ptr = Arc::downgrade(&park_state);
		*thread.state = ThreadState::Parked(park_state);
		weak_ptr
	};
	// FIXME(preemption): any preemption after this point will cause an early park
	// Set the state to `Parked` before calling the closure, so if events are triggered
	// during the closure, the thread already appears parked and will get unparked before yielding
	// Also drop the scheduler lock so that waking doesn't cause a deadlock
	let trigger = WakeTrigger { park_guard: weak_ptr };
	for waker in wakers {
		waker.add_wake_trigger(trigger.clone());
	}
	
	Ok(
		yield_now().expect("State was set to `Parked` before yielding so must have a reason to wake")
	)
}

#[derive(Debug)]
pub(super) struct ParkGaurd {
	thread_id: ThreadId,
}

#[derive(Debug, Clone)]
pub struct WakeTrigger {
	park_guard: Weak<ParkGaurd>,
}

impl PartialEq for WakeTrigger {
	fn eq(&self, other: &Self) -> bool {
		self.park_guard.ptr_eq(&other.park_guard)
	}
}

impl WakeTrigger {
	pub fn wake(&self, reason: WakeReason) {
		if let Some(state) = self.park_guard.upgrade() {
			// FIXME: race condition between upgrading and actually waking which could cause a spurious wakeup
			let tid = state.thread_id;
			let mut guard = super::TASK_LIST.lock();
			let Some(global_thread) = guard.get_mut(&tid) else {
				warn!("Bad thread id {tid:?}");
				return;
			};

			match global_thread.1 {
				PointerState::InScheduler => {
					// todo(smp): actually get the right scheduler instead of the current core
					scheduler::local_scheduler().lock().unpark(tid, reason);
				},
				PointerState::GloballyParked(_) => {
					let PointerState::GloballyParked(mut ptr) = mem::replace(&mut global_thread.1, PointerState::InScheduler) else { unreachable!() };
					
					debug!("Enqueue thread {:?} from global parking lot with reason {reason:?}", ptr.tcb_mut().thread_id);
					*ptr.tcb_mut().state = ThreadState::JustUnparked(reason);
					scheduler::enqueue(ptr);
				},
			};
		}
	}
}

#[derive(Debug, Copy, Clone, Eq, PartialEq)]
#[repr(C)]
pub enum WakeReason {
	Timeout,
	Custom(NonZeroU16),
}

#[derive(Debug)]
#[non_exhaustive]
pub struct ParkError {}

pub trait Waker {
	fn add_wake_trigger(&self, wake_trigger: WakeTrigger);
}
