use crate::threading::yielding::yield_now_inner;

/*
/// Park the current thread until it is woken up
///
/// This will park the thread until a [`WakeTrigger`] for this park event wakes the thread.
/// The kernel guarantees that this function will not return unless either there is an error
/// when parking the thread, or the thread is woken.
///
/// [`WakeTrigger`]s are generated by `park()`, and added to wakers with [`Waker::add_wake_trigger()`].
/// A [`WakeTrigger`] will only wake a thread if it was generated for the current park event. This means
/// that a [`WakeTrigger`] will only wake a thread once, even if [`wake()`](WakeTrigger::wake) is
/// repeatedly called.
///
/// # Errors
///
/// # Examples
///
/// ```no_run
/// use kernel::threading::park;
/// use core::time::Duration;
///
/// static TIMER: TimerWaker = /* ... */;
///
/// // This call will return after one second
/// park(&[&TIMER.waker_for(Duration::from_secs(1)]).expect("failed to park thread");
///
/// // This call will never return, even if the timer interrupt goes off again, unless
/// // there was an error in `park`
/// park(&[]).expect("failed to park thread");
/// unreachable!();
///
/// # Atomicity
///
/// The entirety of a call to `park()` executes atomically - if the thread is woken by a valid [`WakeTrigger`]
/// before `park()` has finished executing, it will act like [`yield_now()`], and a thread will never get stuck
/// waiting for an event that has already occurred.
///
/// This means the following code is guaranteed to always make progress:
/// ```rust
/// # use kernel::non_zero;
/// use kernel::threading::{park, WakeReason, Waker, WakeTrigger};
/// 
/// struct ImmediateWaker;
/// 
/// impl Waker for ImmediateWaker {
///     fn add_wake_trigger(&self, wake_trigger: WakeTrigger) {
///         wake_trigger.wake(WakeReason::Custom(non_zero!(1)));
///     }
/// }
///
/// park(&[&ImmediateWaker]).expect("failed to park thread");
/// ```
pub fn park(wakers: &[&dyn Waker]) -> Result<WakeReason, ParkError> {
	// FIXME(preemption): any preemption after this point will cause an early park
	// Set the state to `Parked` before calling the closure, so if events are triggered
	// during the closure, the thread already appears parked and will get unparked before yielding
	// Also drop the scheduler lock so that waking doesn't cause a deadlock
	Ok(maybe_park(|trigger| {
		for waker in wakers {
			waker.add_wake_trigger(trigger.clone());
		}
		None::<()>
	}).expect_err("`park` always parks thread"))
}*/

#[unsafe(export_name = "__popcorn_async_park_inner_yield")]
fn yield_from_park() {
	yield_now_inner(true);
}
