[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# main depedencies
bitflags = { version = "2.3.1", features = [] }
log = { version = "0.4.20", features = ["max_level_info", "release_max_level_info"] }
derive_more = "0.99.17"
unwinding = { git = "https://github.com/popcorn-2/unwinding.git", default-features = false, features = ["unwinder", "panic", "personality", "fde-static", "hide-trace"] }
acpi = {  version = "5.0.0", default-features = false }
bit_field = "0.10.2"
paste = "1.0.14"
num_enum = { version = "0.7.2", default-features = false }
minicov = { version = "0.3", optional = true }
hashbrown = { version = "0.14.5" }
itertools = { version = "0.14.0", default-features = false, features = ["use_alloc"] }
slab = { version = "0.4.10", default-features = false }
futures = { version = "0.3.31", default-features = false }

# kernel repo deps
kernel_api = { path = "../kernel_api" }
utils = { path = "../utils" }
elf = { version = "0.1.0", path = "../elf" }

# module shims
arena_heap = { path = "../arena_heap" }
bitmap_allocator = { path = "../bitmap_allocator" }
linked_list_allocator = { version = "0.1.0", path = "../linked_list_allocator" }
oneshot = { version = "0.1.11", default-features = false, features = ["async"] }

[dev-dependencies]
minicov = "0.3"
test = { path = "../test_harness" }

[build-dependencies]
pipc = { git = "https://github.com/popcorn-2/pipc.git" }

[features]
default = []
junit_test_out = []
preemptive = []
"log.scheduler" = []
kasan = [ "unwinding/kasan", "kernel_api/kasan", "linked_list_allocator/kasan" ]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kernel_version, values("0.1.0"))', 'cfg(kasan, values(none()))'] }
