[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# main depedencies
bitflags = { version = "2.3.1", features = [] }
log = { version = "0.4.20", features = ["max_level_trace", "release_max_level_debug"] }
derive_more = "2.1.1"
unwinding = { git = "https://github.com/popcorn-2/unwinding.git", default-features = false, features = ["unwinder", "panic", "personality", "fde-static", "hide-trace"] }
acpi = {  version = "6.1.1", default-features = false }
bit_field = "0.10.2"
minicov = { version = "0.3", optional = true }
slab = { version = "0.4.10", default-features = false }

# kernel repo deps
kernel_api = { path = "../kernel_api" }
utils = { path = "../utils" }

# module shims
arena_heap = { path = "../arena_heap" }
bitmap_allocator = { path = "../bitmap_allocator" }
linked_list_allocator = { version = "0.1.0", path = "../linked_list_allocator" }

[dev-dependencies]
minicov = "0.3"
test = { path = "../test_harness" }

[build-dependencies]
pipc = { git = "https://github.com/popcorn-2/pipc.git" }

[features]
default = []
junit_test_out = []
preemptive = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kernel_version, values("0.1.0"))', 'cfg(kasan, values(none()))'] }
