[env]
DEP_LV_CONFIG_PATH = { relative = true, value = "bootloader/lvgl" }
CFLAGS = { value = "-D_FORTIFY_SOURCE=0 -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/libpng/include/libpng16" }
