[package]
name = "linked_list_allocator"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kernel_api = { version = "1.1.0", path = "../kernel_api" }
log = "0.4.21"

[features]
kasan = []

[lints]
workspace = true
