use core::num::NonZero;
use kernel_api::num::ufat;
use kernel_api::sync::LazyLock;
use crate::arch::x86_64::gdt::Gdt;
use super::handler::Handler;

pub static IDT: LazyLock<Idt> = LazyLock::new(|| {
	Idt([
		Entry::new(Handler::<0>::handler, None, 0),
		Entry::new(Handler::<1>::handler, None, 0),
		Entry::new(Handler::<2>::handler, None, 0),
		Entry::new(Handler::<3>::handler, None, 3),
		Entry::new(Handler::<4>::handler, None, 0),
		Entry::new(Handler::<5>::handler, None, 0),
		Entry::new(Handler::<6>::handler, None, 0),
		Entry::new(Handler::<7>::handler, None, 0),
		Entry::new(Handler::<8>::handler, Some(const { NonZero::new(1).unwrap() }), 0),
		Entry::new(Handler::<9>::handler, None, 0),
		Entry::new(Handler::<10>::handler, None, 0),
		Entry::new(Handler::<11>::handler, None, 0),
		Entry::new(Handler::<12>::handler, None, 0),
		Entry::new(Handler::<13>::handler, None, 0),
		Entry::new(Handler::<14>::handler, None, 0),
		Entry::new(Handler::<15>::handler, None, 0),
		Entry::new(Handler::<16>::handler, None, 0),
		Entry::new(Handler::<17>::handler, None, 0),
		Entry::new(Handler::<18>::handler, None, 0),
		Entry::new(Handler::<19>::handler, None, 0),
		Entry::new(Handler::<20>::handler, None, 0),
		Entry::new(Handler::<21>::handler, None, 0),
		Entry::new(Handler::<22>::handler, None, 0),
		Entry::new(Handler::<23>::handler, None, 0),
		Entry::new(Handler::<24>::handler, None, 0),
		Entry::new(Handler::<25>::handler, None, 0),
		Entry::new(Handler::<26>::handler, None, 0),
		Entry::new(Handler::<27>::handler, None, 0),
		Entry::new(Handler::<28>::handler, None, 0),
		Entry::new(Handler::<29>::handler, None, 0),
		Entry::new(Handler::<30>::handler, None, 0),
		Entry::new(Handler::<31>::handler, None, 0),
		Entry::new(Handler::<32>::handler, None, 0),
		Entry::new(Handler::<33>::handler, None, 0),
		Entry::new(Handler::<34>::handler, None, 0),
		Entry::new(Handler::<35>::handler, None, 0),
		Entry::new(Handler::<36>::handler, None, 0),
		Entry::new(Handler::<37>::handler, None, 0),
		Entry::new(Handler::<38>::handler, None, 0),
		Entry::new(Handler::<39>::handler, None, 0),
		Entry::new(Handler::<40>::handler, None, 0),
		Entry::new(Handler::<41>::handler, None, 0),
		Entry::new(Handler::<42>::handler, None, 0),
		Entry::new(Handler::<43>::handler, None, 0),
		Entry::new(Handler::<44>::handler, None, 0),
		Entry::new(Handler::<45>::handler, None, 0),
		Entry::new(Handler::<46>::handler, None, 0),
		Entry::new(Handler::<47>::handler, None, 0),
		Entry::new(Handler::<48>::handler, None, 0),
		Entry::new(Handler::<49>::handler, None, 0),
		Entry::new(Handler::<50>::handler, None, 0),
		Entry::new(Handler::<51>::handler, None, 0),
		Entry::new(Handler::<52>::handler, None, 0),
		Entry::new(Handler::<53>::handler, None, 0),
		Entry::new(Handler::<54>::handler, None, 0),
		Entry::new(Handler::<55>::handler, None, 0),
		Entry::new(Handler::<56>::handler, None, 0),
		Entry::new(Handler::<57>::handler, None, 0),
		Entry::new(Handler::<58>::handler, None, 0),
		Entry::new(Handler::<59>::handler, None, 0),
		Entry::new(Handler::<60>::handler, None, 0),
		Entry::new(Handler::<61>::handler, None, 0),
		Entry::new(Handler::<62>::handler, None, 0),
		Entry::new(Handler::<63>::handler, None, 0),
		Entry::new(Handler::<64>::handler, None, 0),
		Entry::new(Handler::<65>::handler, None, 0),
		Entry::new(Handler::<66>::handler, None, 0),
		Entry::new(Handler::<67>::handler, None, 0),
		Entry::new(Handler::<68>::handler, None, 0),
		Entry::new(Handler::<69>::handler, None, 0),
		Entry::new(Handler::<70>::handler, None, 0),
		Entry::new(Handler::<71>::handler, None, 0),
		Entry::new(Handler::<72>::handler, None, 0),
		Entry::new(Handler::<73>::handler, None, 0),
		Entry::new(Handler::<74>::handler, None, 0),
		Entry::new(Handler::<75>::handler, None, 0),
		Entry::new(Handler::<76>::handler, None, 0),
		Entry::new(Handler::<77>::handler, None, 0),
		Entry::new(Handler::<78>::handler, None, 0),
		Entry::new(Handler::<79>::handler, None, 0),
		Entry::new(Handler::<80>::handler, None, 0),
		Entry::new(Handler::<81>::handler, None, 0),
		Entry::new(Handler::<82>::handler, None, 0),
		Entry::new(Handler::<83>::handler, None, 0),
		Entry::new(Handler::<84>::handler, None, 0),
		Entry::new(Handler::<85>::handler, None, 0),
		Entry::new(Handler::<86>::handler, None, 0),
		Entry::new(Handler::<87>::handler, None, 0),
		Entry::new(Handler::<88>::handler, None, 0),
		Entry::new(Handler::<89>::handler, None, 0),
		Entry::new(Handler::<90>::handler, None, 0),
		Entry::new(Handler::<91>::handler, None, 0),
		Entry::new(Handler::<92>::handler, None, 0),
		Entry::new(Handler::<93>::handler, None, 0),
		Entry::new(Handler::<94>::handler, None, 0),
		Entry::new(Handler::<95>::handler, None, 0),
		Entry::new(Handler::<96>::handler, None, 0),
		Entry::new(Handler::<97>::handler, None, 0),
		Entry::new(Handler::<98>::handler, None, 0),
		Entry::new(Handler::<99>::handler, None, 0),
		Entry::new(Handler::<100>::handler, None, 0),
		Entry::new(Handler::<101>::handler, None, 0),
		Entry::new(Handler::<102>::handler, None, 0),
		Entry::new(Handler::<103>::handler, None, 0),
		Entry::new(Handler::<104>::handler, None, 0),
		Entry::new(Handler::<105>::handler, None, 0),
		Entry::new(Handler::<106>::handler, None, 0),
		Entry::new(Handler::<107>::handler, None, 0),
		Entry::new(Handler::<108>::handler, None, 0),
		Entry::new(Handler::<109>::handler, None, 0),
		Entry::new(Handler::<110>::handler, None, 0),
		Entry::new(Handler::<111>::handler, None, 0),
		Entry::new(Handler::<112>::handler, None, 0),
		Entry::new(Handler::<113>::handler, None, 0),
		Entry::new(Handler::<114>::handler, None, 0),
		Entry::new(Handler::<115>::handler, None, 0),
		Entry::new(Handler::<116>::handler, None, 0),
		Entry::new(Handler::<117>::handler, None, 0),
		Entry::new(Handler::<118>::handler, None, 0),
		Entry::new(Handler::<119>::handler, None, 0),
		Entry::new(Handler::<120>::handler, None, 0),
		Entry::new(Handler::<121>::handler, None, 0),
		Entry::new(Handler::<122>::handler, None, 0),
		Entry::new(Handler::<123>::handler, None, 0),
		Entry::new(Handler::<124>::handler, None, 0),
		Entry::new(Handler::<125>::handler, None, 0),
		Entry::new(Handler::<126>::handler, None, 0),
		Entry::new(Handler::<127>::handler, None, 0),
		Entry::new(Handler::<128>::handler, None, 0),
		Entry::new(Handler::<129>::handler, None, 0),
		Entry::new(Handler::<130>::handler, None, 0),
		Entry::new(Handler::<131>::handler, None, 0),
		Entry::new(Handler::<132>::handler, None, 0),
		Entry::new(Handler::<133>::handler, None, 0),
		Entry::new(Handler::<134>::handler, None, 0),
		Entry::new(Handler::<135>::handler, None, 0),
		Entry::new(Handler::<136>::handler, None, 0),
		Entry::new(Handler::<137>::handler, None, 0),
		Entry::new(Handler::<138>::handler, None, 0),
		Entry::new(Handler::<139>::handler, None, 0),
		Entry::new(Handler::<140>::handler, None, 0),
		Entry::new(Handler::<141>::handler, None, 0),
		Entry::new(Handler::<142>::handler, None, 0),
		Entry::new(Handler::<143>::handler, None, 0),
		Entry::new(Handler::<144>::handler, None, 0),
		Entry::new(Handler::<145>::handler, None, 0),
		Entry::new(Handler::<146>::handler, None, 0),
		Entry::new(Handler::<147>::handler, None, 0),
		Entry::new(Handler::<148>::handler, None, 0),
		Entry::new(Handler::<149>::handler, None, 0),
		Entry::new(Handler::<150>::handler, None, 0),
		Entry::new(Handler::<151>::handler, None, 0),
		Entry::new(Handler::<152>::handler, None, 0),
		Entry::new(Handler::<153>::handler, None, 0),
		Entry::new(Handler::<154>::handler, None, 0),
		Entry::new(Handler::<155>::handler, None, 0),
		Entry::new(Handler::<156>::handler, None, 0),
		Entry::new(Handler::<157>::handler, None, 0),
		Entry::new(Handler::<158>::handler, None, 0),
		Entry::new(Handler::<159>::handler, None, 0),
		Entry::new(Handler::<160>::handler, None, 0),
		Entry::new(Handler::<161>::handler, None, 0),
		Entry::new(Handler::<162>::handler, None, 0),
		Entry::new(Handler::<163>::handler, None, 0),
		Entry::new(Handler::<164>::handler, None, 0),
		Entry::new(Handler::<165>::handler, None, 0),
		Entry::new(Handler::<166>::handler, None, 0),
		Entry::new(Handler::<167>::handler, None, 0),
		Entry::new(Handler::<168>::handler, None, 0),
		Entry::new(Handler::<169>::handler, None, 0),
		Entry::new(Handler::<170>::handler, None, 0),
		Entry::new(Handler::<171>::handler, None, 0),
		Entry::new(Handler::<172>::handler, None, 0),
		Entry::new(Handler::<173>::handler, None, 0),
		Entry::new(Handler::<174>::handler, None, 0),
		Entry::new(Handler::<175>::handler, None, 0),
		Entry::new(Handler::<176>::handler, None, 0),
		Entry::new(Handler::<177>::handler, None, 0),
		Entry::new(Handler::<178>::handler, None, 0),
		Entry::new(Handler::<179>::handler, None, 0),
		Entry::new(Handler::<180>::handler, None, 0),
		Entry::new(Handler::<181>::handler, None, 0),
		Entry::new(Handler::<182>::handler, None, 0),
		Entry::new(Handler::<183>::handler, None, 0),
		Entry::new(Handler::<184>::handler, None, 0),
		Entry::new(Handler::<185>::handler, None, 0),
		Entry::new(Handler::<186>::handler, None, 0),
		Entry::new(Handler::<187>::handler, None, 0),
		Entry::new(Handler::<188>::handler, None, 0),
		Entry::new(Handler::<189>::handler, None, 0),
		Entry::new(Handler::<190>::handler, None, 0),
		Entry::new(Handler::<191>::handler, None, 0),
		Entry::new(Handler::<192>::handler, None, 0),
		Entry::new(Handler::<193>::handler, None, 0),
		Entry::new(Handler::<194>::handler, None, 0),
		Entry::new(Handler::<195>::handler, None, 0),
		Entry::new(Handler::<196>::handler, None, 0),
		Entry::new(Handler::<197>::handler, None, 0),
		Entry::new(Handler::<198>::handler, None, 0),
		Entry::new(Handler::<199>::handler, None, 0),
		Entry::new(Handler::<200>::handler, None, 0),
		Entry::new(Handler::<201>::handler, None, 0),
		Entry::new(Handler::<202>::handler, None, 0),
		Entry::new(Handler::<203>::handler, None, 0),
		Entry::new(Handler::<204>::handler, None, 0),
		Entry::new(Handler::<205>::handler, None, 0),
		Entry::new(Handler::<206>::handler, None, 0),
		Entry::new(Handler::<207>::handler, None, 0),
		Entry::new(Handler::<208>::handler, None, 0),
		Entry::new(Handler::<209>::handler, None, 0),
		Entry::new(Handler::<210>::handler, None, 0),
		Entry::new(Handler::<211>::handler, None, 0),
		Entry::new(Handler::<212>::handler, None, 0),
		Entry::new(Handler::<213>::handler, None, 0),
		Entry::new(Handler::<214>::handler, None, 0),
		Entry::new(Handler::<215>::handler, None, 0),
		Entry::new(Handler::<216>::handler, None, 0),
		Entry::new(Handler::<217>::handler, None, 0),
		Entry::new(Handler::<218>::handler, None, 0),
		Entry::new(Handler::<219>::handler, None, 0),
		Entry::new(Handler::<220>::handler, None, 0),
		Entry::new(Handler::<221>::handler, None, 0),
		Entry::new(Handler::<222>::handler, None, 0),
		Entry::new(Handler::<223>::handler, None, 0),
		Entry::new(Handler::<224>::handler, None, 0),
		Entry::new(Handler::<225>::handler, None, 0),
		Entry::new(Handler::<226>::handler, None, 0),
		Entry::new(Handler::<227>::handler, None, 0),
		Entry::new(Handler::<228>::handler, None, 0),
		Entry::new(Handler::<229>::handler, None, 0),
		Entry::new(Handler::<230>::handler, None, 0),
		Entry::new(Handler::<231>::handler, None, 0),
		Entry::new(Handler::<232>::handler, None, 0),
		Entry::new(Handler::<233>::handler, None, 0),
		Entry::new(Handler::<234>::handler, None, 0),
		Entry::new(Handler::<235>::handler, None, 0),
		Entry::new(Handler::<236>::handler, None, 0),
		Entry::new(Handler::<237>::handler, None, 0),
		Entry::new(Handler::<238>::handler, None, 0),
		Entry::new(Handler::<239>::handler, None, 0),
		Entry::new(Handler::<240>::handler, None, 0),
		Entry::new(Handler::<241>::handler, None, 0),
		Entry::new(Handler::<242>::handler, None, 0),
		Entry::new(Handler::<243>::handler, None, 0),
		Entry::new(Handler::<244>::handler, None, 0),
		Entry::new(Handler::<245>::handler, None, 0),
		Entry::new(Handler::<246>::handler, None, 0),
		Entry::new(Handler::<247>::handler, None, 0),
		Entry::new(Handler::<248>::handler, None, 0),
		Entry::new(Handler::<249>::handler, None, 0),
		Entry::new(Handler::<250>::handler, None, 0),
		Entry::new(Handler::<251>::handler, None, 0),
		Entry::new(Handler::<252>::handler, None, 0),
		Entry::new(Handler::<253>::handler, None, 0),
		Entry::new(Handler::<254>::handler, None, 0),
		Entry::new(Handler::<255>::handler, None, 0),
	])
});

#[repr(C)]
pub struct Idt([Entry; 256]);

impl Idt {
	pub fn load(&'static self) {
		#[repr(C, packed)]
		struct Pointer {
			limit: u16,
			address: &'static Idt,
		}

		let ptr = Pointer {
			limit: size_of::<Idt>().truncate::<u16>() - 1,
			address: self,
		};

		unsafe {
			core::arch::asm!(
				"lidt [{pointer}]",
				pointer = in(reg) &ptr,
			);
		}
	}
}

#[repr(C)]
pub struct Entry(ufat);

impl Entry {
	fn new(
		handler: unsafe extern "custom" fn(),
		ist: Option<NonZero<u8>>,
		dpl: u8,
	) -> Self {
		let addr = handler as usize;
		let ist = ist.map_or(0, NonZero::get);
		assert!(ist < 8, "only 7 IST stacks");
		assert!(dpl < 4, "DPL can only be 0, 1, 2, 3");

		Self(ufat::new(
			addr >> 32,
			addr & 0xFFFF |
			Gdt::KERNEL_CODE_SEGMENT << 16 |
			usize::from(ist) << 32 |
			0xE << 40 |
			usize::from(dpl) << 45 |
			1 << 47 |
			(addr >> 16) << 48,
		))
	}
}
