[package]
name = "elf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.3"
kernel_api = { path = "../kernel_api", default-features = false }

[features]
testing = []
default = []

[lints]
workspace = true
