[package]
name = "bootloader"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = { version = "2.3.1" }
log = { version = "0.4.17", features = ["max_level_trace", "release_max_level_debug"] }
uefi = { version = "0.39.0", default-features = false, features = ["alloc", "global_allocator"] }
utils = { path = "../utils" }
elf = { version = "0.1.0", path = "../elf" }
kernel_api = { version = "1.1.0", path = "../kernel_api", default-features = false }
