name: Build and test

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out'
        uses: actions/checkout@v4
      - name: 'Install multilib'
        run: |
          sudo apt install -y gcc-multilib g++-multilib
      - name: 'Build'
        env:
          CC: clang
          CXX: C++
        run: |
          ./pop.py build --arch x86_64 -v ${{ github.ref == 'refs/heads/trunk' && '--release' || '' }}
      - name: 'Archive live ISO'
        if: success() && github.ref == 'refs/heads/trunk'
        uses: actions/upload-artifact@v3
        with:
          name: Live ISO
          path: |
            target/debug/popcorn2.iso
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out'
        uses: actions/checkout@v4
      - name: 'Install multilib and qemu'
        run: |
          sudo apt install -y gcc-multilib g++-multilib qemu-system
      - name: 'Run tests'
        env:
          CC: clang
          CXX: C++
        run: |
          ./pop.py test --arch x86_64 -v --coverage coverage.profraw --accel kvm
      - name: 'Archive coverage'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test coverage
          path: |
            coverage.profraw
