name: Build and test

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out'
        uses: actions/checkout@v4
      - name: 'Build'
        run: |
          ./pop.py build --arch x86_64 -j1 -v
      - name: 'Archive live ISO'
        uses: actions/upload-artifact@v3
        with:
          name: Live ISO
          path: |
            target/debug/popcorn2.iso
