name: Build and test

on:
  repository_dispatch:
    types: [ gerrit-patchset ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/trunk' }}

jobs:
  bootloader:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out'
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'
          ref: ${{ github.event.client_payload.patchSet.ref }}
      - name: 'Install tooling'
        uses: ./.github/actions/install-tooling
      - uses: r7kamura/rust-problem-matchers@v1
      - name: 'Run clippy'
        continue-on-error: true
        run: ./xbstrap/pop --sysroot=sysroot --target x86_64-unknown-popcorn --local-source @core/kernel=. run @core/bootloader cargo clippy -- -Dwarnings
      - name: 'Run build'
        run: ./xbstrap/pop --sysroot=sysroot --target x86_64-unknown-popcorn --local-source @core/kernel=. build @core/bootloader
  kernel:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out'
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'
          ref: ${{ github.event.client_payload.patchSet.ref }}
      - name: 'Install tooling'
        uses: ./.github/actions/install-tooling
      - uses: r7kamura/rust-problem-matchers@v1
      - name: 'Run clippy (stable)'
        continue-on-error: true
        run: ./xbstrap/pop --sysroot=sysroot --target x86_64-unknown-popcorn --local-source @core/kernel=. run @core/kernel cargo clippy -p kernel -- -Dwarnings
      - name: 'Check kernel-next'
        run: ./xbstrap/pop --sysroot=sysroot --target x86_64-unknown-popcorn --local-source @core/kernel=. run @core/kernel cargo check -p kernel --all-features
      - name: 'Run build'
        run: ./xbstrap/pop --sysroot=sysroot --target x86_64-unknown-popcorn --local-source @core/kernel=. build @core/kernel

  gerrit-vote:
    runs-on: ubuntu-latest
    needs: [ bootloader, kernel ]
    if: always()
    steps:
      - name: Evaluate Results and Vote
        env:
          CHANGE_NUM: ${{ github.event.client_payload.change_number }}
          PATCH_NUM: ${{ github.event.client_payload.patchset_number }}
          BOOTLOADER_STATUS: ${{ needs.bootloader.result }}
          KERNEL_STATUS: ${{ needs.kernel.result }}
        run: |
          # Check if ALL dependencies succeeded
          if [[ "BOOTLOADER_STATUS" == "success" && "KERNEL_STATUS" == "success" ]]; then
            VOTE=1
            MESSAGE="CI Passed"
          else
            VOTE=-1
            MESSAGE="CI Failed. Bootloader: BOOTLOADER_STATUS | Kernel: KERNEL_STATUS"
          fi
          
          curl -X POST -u "${{ secrets.GERRIT_USERNAME }}:${{ secrets.GERRIT_PASSWORD }}" \
            -H "Content-Type: application/json" \
            -d "{\"labels\": {\"Verified\": $VOTE}, \"message\": \"$MESSAGE\"}" \
            "https://review.gerrithub.io/a/changes/$CHANGE_NUM/revisions/$PATCH_NUM/review"
  # test:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     pull-requests: write
  #   steps:
  #     - name: 'Check out'
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: 'recursive'
  #     - name: 'Install multilib and qemu'
  #       run: |
  #         sudo apt update
  #         sudo apt install -y qemu-system-x86 ovmf
  #     - name: 'Run tests'
  #       env:
  #         CC: clang
  #         CXX: C++
  #         CFLAGS: -I${{ github.workspace }}/deps/edk2/MdePkg/Include -I${{ github.workspace }}/deps/edk2-libc/StdLib/Include -I${{ github.workspace }}/deps/edk2-libc/StdLib/Include/X64
  #       run: |
  #         cp /usr/share/OVMF/OVMF_CODE.fd ./OVMF_CODE.fd
  #         cp /usr/share/OVMF/OVMF_VARS.fd ./OVMF_VARS.fd
  #         ./pop.py test --arch x86_64 -v --coverage coverage.profraw --junit junit.xml
  #     - name: Test Summary
  #       if: success() || failure()
  #       uses: test-summary/action@v2
  #       with:
  #         paths: "junit.xml"
  #         show: "fail, skip"
  #         output: "tests.md"
  #     - name: 'Archive results'
  #       if: success() || failure()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: Test results
  #         path: |
  #           junit.xml
  #     - name: 'Add results to PR'
  #       if: (success() || failure()) && github.event_name == 'pull_request'
  #       uses: mshick/add-pr-comment@v2
  #       with:
  #         message-path: "tests.md"
  #     - name: 'Add results to workflow summary'
  #       if: success() || failure()
  #       run: |
  #         cat tests.md >> $GITHUB_STEP_SUMMARY
  #     - name: 'Archive coverage'
  #       if: success() || failure()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: Test coverage
  #         path: |
  #           coverage.profraw
